# Generated by Django 2.0.5 on 2018-05-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='idProvincia',
            new_name='provincia',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='idColor',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='idModelo',
        ),
        migrations.AddField(
            model_name='carro',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Ciudad'),
        ),
        migrations.AddField(
            model_name='carro',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Color'),
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Modelo'),
        ),
        migrations.AddField(
            model_name='carro',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Provincia'),
        ),
    ]
