# Generated by Django 2.0.5 on 2018-05-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_auto_20180521_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='dueno',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
