# Generated by Django 2.0.5 on 2018-05-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_carro_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='dueno',
        ),
        migrations.AddField(
            model_name='carro',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Persona'),
        ),
    ]
