# Generated by Django 2.0.5 on 2018-05-21 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculo', '0006_persona_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='persona',
        ),
        migrations.AddField(
            model_name='carro',
            name='usuario',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
