# Generated by Django 2.0.5 on 2018-05-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0007_auto_20180521_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='idMarca',
            new_name='marca',
        ),
    ]
