# Generated by Django 2.0.5 on 2018-05-22 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_auto_20180521_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=50)),
                ('chasis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choque', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='carro',
            name='ciudad',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Ciudad'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='color',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Color'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Marca'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Modelo'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='provincia',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Provincia'),
        ),
        migrations.AddField(
            model_name='carro',
            name='inspeccion',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Inspeccion'),
        ),
    ]
