# Generated by Django 2.0.5 on 2018-05-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0009_auto_20180521_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(default='AAA-0000', max_length=10),
        ),
    ]
