# Generated by Django 2.0.5 on 2018-05-22 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0010_carro_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='inspeccion',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='carro',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Carro'),
        ),
    ]
