# Generated by Django 2.0.5 on 2018-05-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0016_auto_20180522_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagen',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(default='AAA-0000', help_text='Ejemplo: XXX-0XXX', max_length=10),
        ),
    ]
