# Generated by Django 2.0.5 on 2018-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0017_auto_20180528_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imagen',
            field=models.ImageField(default='no_image.jpg', upload_to=''),
        ),
    ]
