# Generated by Django 2.0.5 on 2018-05-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0018_auto_20180528_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagen_nombre',
            field=models.CharField(default='no_imagen', max_length=100),
        ),
        migrations.AlterField(
            model_name='carro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
