# Generated by Django 2.0.5 on 2018-05-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0019_auto_20180528_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imagen_nombre',
            field=models.CharField(default='x.jpg', max_length=100),
        ),
    ]
