# Generated by Django 2.0.5 on 2018-05-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0020_auto_20180528_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ant',
            name='carro',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculo.Carro'),
        ),
    ]
